extends:
  [
    'eslint:recommended',
    'plugin:jest/recommended',
    'plugin:@typescript-eslint/recommended',
    'prettier/@typescript-eslint',
    'plugin:prettier/recommended',
    'plugin:functional/external-recommended',
    'plugin:functional/recommended',
    'plugin:import/warnings',
    'plugin:import/errors',
    'plugin:import/typescript',
  ]
plugins: ['@typescript-eslint', 'jest', 'prettier', 'functional', 'import']
env:
  browser: false
  es6: true
  node: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2020
  sourceType: module
  project: './tsconfig.json'
rules:
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
    - avoidEscape: true
      allowTemplateLiterals: true
  semi:
    - error
    - never
  object-curly-spacing:
    - warn
    - always
  functional/functional-parameters: 'off'
  functional/no-conditional-statement:
    - off
  functional/no-expression-statement:
    - off
  import/order:
    - error
